package com.platform.model.ride;

import com.platform.model.enums.ParcelStatus;
import com.platform.model.enums.VehicleCategory;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * A Parcel extends a Trip with physical metadata and OTP-based handshake.
 * Design Principle: Single Responsibility — Parcel only holds delivery
 * data; OTP generation lives in OTPManager.
 */
@Entity
@Table(name = "parcels")
public class Parcel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id", nullable = false)
    private Trip trip;

    // Item metadata (synopsis section 4.1)
    private Double weight;
    private String dimensions;         // e.g. "30x20x15 cm"
    private String contentDescription;

    // Receiver details (synopsis section 4.2)
    @Column(nullable = false)
    private String receiverName;

    @Column(nullable = false)
    private String receiverContact;

    private String deliveryOtp;        // generated by OTPManager, sent to receiver

    @Enumerated(EnumType.STRING)
    private ParcelStatus parcelStatus = ParcelStatus.CREATED;

    @Enumerated(EnumType.STRING)
    private VehicleCategory vehicleCategory;

    private String deliveryOtp_input;  // what driver enters; validated against deliveryOtp

    private LocalDateTime statusUpdatedAt;

    @PrePersist @PreUpdate
    protected void onUpdate() {
        statusUpdatedAt = LocalDateTime.now();
    }

    /**
     * Validates the OTP entered by the driver against the one sent to receiver.
     * Must match for transition to DELIVERED (synopsis section 4.3).
     */
    public boolean verifyOtp(String input) {
        return deliveryOtp != null && deliveryOtp.equals(input);
    }

    /**
     * Validates vehicle suitability for this parcel's weight/dimensions.
     * Basic rule: BIKE category cannot carry parcels over 10 kg.
     */
    public boolean isValidForCategory(VehicleCategory category) {
        if (category == VehicleCategory.BIKE && weight != null && weight > 10.0) {
            return false;
        }
        return true;
    }

    // --- Getters and Setters ---

    public Long getId() { return id; }

    public Trip getTrip() { return trip; }
    public void setTrip(Trip trip) { this.trip = trip; }

    public Double getWeight() { return weight; }
    public void setWeight(Double weight) { this.weight = weight; }

    public String getDimensions() { return dimensions; }
    public void setDimensions(String dimensions) { this.dimensions = dimensions; }

    public String getContentDescription() { return contentDescription; }
    public void setContentDescription(String contentDescription) {
        this.contentDescription = contentDescription;
    }

    public String getReceiverName() { return receiverName; }
    public void setReceiverName(String receiverName) { this.receiverName = receiverName; }

    public String getReceiverContact() { return receiverContact; }
    public void setReceiverContact(String receiverContact) { this.receiverContact = receiverContact; }

    public String getDeliveryOtp() { return deliveryOtp; }
    public void setDeliveryOtp(String deliveryOtp) { this.deliveryOtp = deliveryOtp; }

    public ParcelStatus getParcelStatus() { return parcelStatus; }
    public void setParcelStatus(ParcelStatus parcelStatus) { this.parcelStatus = parcelStatus; }

    public VehicleCategory getVehicleCategory() { return vehicleCategory; }
    public void setVehicleCategory(VehicleCategory vehicleCategory) {
        this.vehicleCategory = vehicleCategory;
    }

    public LocalDateTime getStatusUpdatedAt() { return statusUpdatedAt; }
}